### ISSUE TITLE
Model_1 releases

### ISSUE THREAD

**Issue by JoyceYJ01** [calico/AAC_scoring#26]
Hello, I’ve been trying to reproduce some parts of your work. And noticed that the Model 2 pipeline works all right and seems to capture the abdominal aorta region quite accurately (Great!). 
However, the Model 1 pipeline seems not to produce any results, probably because the trained segmentation and regression model files are not available to public access? (under https://github.com/calico/AAC_scoring/releases, there isn’t anything). Therefore,
1.	may I ask you a favour to release the trained Model 1 weights/parameters?
2.	And would you mind telling me what parameter you used for converting DICOMs to PNGs? (I have downloaded DXA images from UK Biobank, and Is ‘image_scaled = (np.maximum(image,0) / image.max()) * 255.0’ good enough for all Dicoms' converting process?)

Many thanks!

**Comment by eugenemel** [comment]
Hi, we believe we fixed this issued, could you try again.
